export default {
    en: {
		'注册登录': 'Register/Login',
		登录: 'Login',
		注册: 'Register',
		登录账号: 'Login account',
		请输入登录账号: 'Please enter the login account',
		请输入登录密码: 'Please enter the password',
		请再次输入密码: 'Please enter the passwordag ain',
		用户服务协议及隐私保护策略: 'User service agreement and privacy protection policy',
		登录密码: 'Login Password',
		确认密码: 'Confirm Password',
		注册成功: 'Register was successful！',
		注册失败: 'Registration failed. Please try again!',
		登录成功: 'Login success',
		登录失败: 'Login failed',
		请阅读并同意用户服务协议及隐私保护策略: 'Please read and agree to the 《User service agreement and privacy protection policy》',
		手机或密码错误: 'Wrong phone or password',
		两次输入密码不同: 'The two passwords are different',
		myorder: 'My Order',
		logout: 'Logout',
		english: '中文',
		activityTitle: 'How to use digital tools to empower a 10-year-old existing equipment to realize fully intelligent production?',
		activityP1: 'How can the existing equipment that has already been invested keep up with the pace of digitalization? Let’s learn about the new generation of smart factories, how to transform an ordinary used machine, after intelligently controlling the brain, vision, hands and feet, into a one that can quickly undertake personal customization, real-time feedback, process stability, and online intelligent detection and marking The protagonist of the intelligent production line.',
		
		strategyTitle: 'Activity strategy',
		strategy1: 'Submit a personalized customized order to the platform.',
		strategy2: 'ERP system automatically takes orders.',
		strategy3: 'MES system automatically schedules orders.',
		strategy4: 'Machines are produced according to customized requirements, and the production process and optical inspection results can be viewed online.',
		strategy5: 'The system will automatically send a pick-up notice after production is completed, and pick up with the pick-up code.',
		
		名片夹: 'Business Card Holder',
		真实姓名: 'Actual Name',
		请输入真实姓名: 'Please enter Actual Name',
		联系方式: 'Phone Number',
		请输入联系方式: 'Please enter your contact information',
		联系地址: 'Contact Address',
		产品颜色: 'Product Color',
		产品数量: 'Quantity',
		产品刻字: 'Product lettering',
		微信二维码: 'WeChat QR Code',
		提交: 'Submit',
		请选择地址:'Please select an address',
		请选择产品颜色:'Please choose product color',
		请输入产品刻字:'Please input product lettering',
		'8个字以内': 'less than 8 characters',
		请先登录: 'Please log in first',
		
		暂无订单: 'No Order',
		订单编号: 'Order Number',
		产品名称: 'Product name',
		提交订单: 'Submit Order',
		系统排产: 'System Scheduling',
		生产完毕: 'Complete Production',
		待取件: 'Pickup',
	},
    zh: {
		'注册登录': '注册/登录',
		登录: '登录',
		注册: '注册',
		登录账号: '登录账号',
		请输入登录账号: '请输入登录账号',
		请输入登录密码: '请输入登录密码',
		请再次输入密码: '请再次输入密码',
		用户服务协议及隐私保护策略: '用户服务协议及隐私保护策略',
		请阅读并同意用户服务协议及隐私保护策略: '请阅读并同意《用户服务协议及隐私保护策略》',
		手机或密码错误: '手机或密码错误',
		两次输入密码不同: '两次输入密码不同',
		登录密码: '登录密码',
		确认密码: '确认密码',
		注册成功: '注册成功！',
		注册失败: '注册失败，请重试！',
		登录成功: '登录成功!',
		登录失败: '登录失败!',
		myorder: '我的订单',
		logout: '退出登录',
		english: 'ENGLISH',
		activityTitle: '如何用数字工具赋能一台 10 年现有设备实现全智能生产？',
		activityP1: '已经投资的既有设备该如何跟上数字化的脚步？来了解新世代的智能工厂，如何将一台平凡的中古机，在智能化了控制的大脑，视觉以及手脚之后，摇身一变成为能快速承接个人订制、实时反馈工艺稳定、在线智能检测打标的全智能生产线主角。',
        
		strategyTitle: '活动体验攻略',
		strategy1: '向平台提交个性化定制订单',
        strategy2: 'ERP系统自动接单',
        strategy3: 'MES系统自动排单',
        strategy4: '机器按照定制化需求生产，可在线查看生产过程和光学检测结果',
        strategy5: '生产完毕，系统自动发出取件通知，凭取件码领取',
		
		名片夹: '名片夹',
		真实姓名: '真实姓名',
		请输入真实姓名: '请输入真实姓名',
		联系方式: '联系方式',
		请输入联系方式: '请输入联系方式',
		联系地址: '联系地址',
		产品颜色: '产品颜色',
		产品数量: '产品数量',
		产品刻字: '产品刻字',
		微信二维码: '微信二维码',
		提交: '提交',
		请选择地址:'请选择地址',
		请选择产品颜色:'请选择产品颜色',
		请输入产品刻字:'请输入产品刻字',
		请先登录: '请先登录',
		
		暂无订单: '暂无订单',
		订单编号: '订单编号',
		产品名称: '产品名称',
		
		提交订单: '提交订单',
		系统排产: '系统排产',
		生产完毕: '生产完毕',
		待取件: '待取件',
    },
}